# Generated by Django 5.0.3 on 2024-03-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(default='Here will be some instrutctions'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "INSERT INTO recipies_recipe (title, instruction)"
            "VALUES ('Borsch', 'Borsch instructions');",
            "DELETE FROM recipies_recipe WHERE title='Borsch';"
        ),
    ]
