# Generated by Django 5.0.3 on 2024-03-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('recipies', '0004_recipe_author_favoriterecipe_recipe_liked_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipies', to='categories.category'),
        ),
    ]
